**

!POC/
!POC/build/
!POC/build/carchief_website.html
!POC/build/carchief_customer_backend.html
!POC/build/carchief_staff_backend.html
!POC/public/
!POC/public/favicon.svg
!POC/public/manifest.webmanifest
!POC/public/sw.js
!POC/package.json
!POC/package-lock.json
!POC/server.ts

!docker/
!docker/poc/
!docker/poc/nginx.conf
!docker/poc/reset.html
